PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex: <http://example.com/>
PREFIX voc: <http://example.com/voc/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?Product ?label ?category ?reachCompliant ?recycledScore
WHERE {
        ?Product a voc:Product ;
            rdfs:label ?label ; 
            voc:category ?category ;
            voc:reachCompliant ?reachCompliant; 
            voc:recycledScore ?recycledScore .
 }
