PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex: <http://example.com/>
PREFIX voc: <http://example.com/voc/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?ProductLabel ?reachCompliant ?recycledScore ?volumeML ?percentageBenzene ?percentageRecycled ?originCountry
WHERE {
    ?Product a      voc:Product ;
        voc:category $Category ;
        rdfs:label  ?ProductLabel ;
        voc:reachCompliant  ?reachCompliant ;
        voc:recycledScore  ?recycledScore ;
        voc:volumeML ?volumeML ;
        voc:percentageBenzene ?percentageBenzene ;
        voc:percentageRecycled ?percentageRecycled ;
        voc:originCountry ?originCountry .
 }
